/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.VendaCursos;

import com.example.VendaCursos.database.ConnectS;
import com.example.VendaCursos.view.LoginScreen;


public class App {

    public static void main(String[] args) {
        new LoginScreen().setVisible(true);
    }
}
